### PR TITLE
feat(cli,modes): add venv_path option in init and build to enable users to use existing virtualenv.

### LINKED ISSUE #18: integration into existing virtual environment
Hi, I'm a new user of this project. 
I wonder if this project intends to support usecase where users have existing virutal environment. 
FYI, I am trying to integrate this project as our local development environment. Since we already installed airflow package, it doesn't need to re-install airflow dependencies.

### PR DESCRIPTION
**Pull request by ahnsv**
Resolve #18

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
Thanks for opening the PR, let's see what the tests say :)

**Comment by ahnsv** [comment]
@kaxil Hi. 

I made changes where I 1) added a `venv_path` option in init and build command 2) let each command use virtualenv from its global config instead of `project_path + ".venv/"` (which was the default) 3) came up with some utility functions to make it DRY. 

Please feel free to give me some feedbacks. Thanks.

**Comment by kaxil** [comment]
Awesome, I am out tomorrow but let me review it in the next few days.

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Thank you very much @ahnsv and congratulations on your first contribution 🎉

**Comment by ahnsv** [comment]
I'v been MIA for couple days. Sounds amazing 👍

**Pull request merged**
